# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Vivek Kaushal
        # Author title
        author_title: Research Student | Developer | MLOps Engineer
        # Author's current location
        location: Hyderabad, India
        # URL or path to the avatar image
        avatar: 'images/avatar.jpg' 
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://twitter.com/vi_kaushal?ref_src=twsrc%5Etfw'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/kaushalvivek'
            # Instagram:
            #     icon: fab fa-instagram
            #     url: 'https://instagram.com/vivekkaushal'
            LinkedIn:
                icon: fab fa-linkedin
                url : 'https://linkedin.com/in/vivekkaushal1998'
            # Facebook:
            #     icon: fab fa-facebook
            #     url: 'https://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/vi_kaushal'
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags